# Build stage
FROM node:18-alpine as build

WORKDIR /app
COPY package*.json ./
RUN npm install
COPY . .
ARG REACT_APP_BASE_URL
ARG REACT_APP_IMG_PATH
ARG NODE_ENV
ARG REACT_APP_GA_TRACKING_ID_PROD
ARG REACT_APP_GA_TRACKING_ID_STAGING
ENV REACT_APP_BASE_URL=$REACT_APP_BASE_URL
ENV REACT_APP_IMG_PATH=$REACT_APP_IMG_PATH
ENV NODE_ENV=$NODE_ENV
ENV REACT_APP_GA_TRACKING_ID_PROD=$REACT_APP_GA_TRACKING_ID_PROD
ENV REACT_APP_GA_TRACKING_ID_STAGING=$REACT_APP_GA_TRACKING_ID_STAGING
RUN npm run build

# Production stage
FROM nginx:alpine
COPY nginx.conf /etc/nginx/conf.d/default.conf
COPY --from=build /app/build /usr/share/nginx/html
EXPOSE 80
CMD ["nginx", "-g", "daemon off;"] 