/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as UnauthorizedImport } from './routes/unauthorized'
import { Route as DashboardImport } from './routes/_dashboard'
import { Route as AuthImport } from './routes/_auth'
import { Route as IndexImport } from './routes/index'
import { Route as DashboardTeamImport } from './routes/_dashboard/team'
import { Route as DashboardStudentClubsImport } from './routes/_dashboard/student-clubs'
import { Route as DashboardStudentChaptersImport } from './routes/_dashboard/student-chapters'
import { Route as DashboardStudentCampusImport } from './routes/_dashboard/student-campus'
import { Route as DashboardRolesImport } from './routes/_dashboard/roles'
import { Route as DashboardProgramsImport } from './routes/_dashboard/programs'
import { Route as DashboardProgramAlumnisImport } from './routes/_dashboard/program-alumnis'
import { Route as DashboardOrganizationalStructureImport } from './routes/_dashboard/organizational-structure'
import { Route as DashboardMembersImport } from './routes/_dashboard/members'
import { Route as DashboardMajorCampusesImport } from './routes/_dashboard/major-campuses'
import { Route as DashboardHistoriesImport } from './routes/_dashboard/histories'
import { Route as DashboardHelpCenterImport } from './routes/_dashboard/help-center'
import { Route as DashboardFaqsImport } from './routes/_dashboard/faqs'
import { Route as DashboardExternalOrganizationsImport } from './routes/_dashboard/external-organizations'
import { Route as DashboardEventsImport } from './routes/_dashboard/events'
import { Route as DashboardEditProfileImport } from './routes/_dashboard/edit-profile'
import { Route as DashboardDashboardImport } from './routes/_dashboard/dashboard'
import { Route as AuthLoginImport } from './routes/_auth/login'
import { Route as DashboardRegistrantsEventidImport } from './routes/_dashboard/registrants.$event_id'
import { Route as DashboardEventDataEventidImport } from './routes/_dashboard/event-data.$event_id'

// Create/Update Routes

const UnauthorizedRoute = UnauthorizedImport.update({
  id: '/unauthorized',
  path: '/unauthorized',
  getParentRoute: () => rootRoute,
} as any)

const DashboardRoute = DashboardImport.update({
  id: '/_dashboard',
  getParentRoute: () => rootRoute,
} as any)

const AuthRoute = AuthImport.update({
  id: '/_auth',
  getParentRoute: () => rootRoute,
} as any)

const IndexRoute = IndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const DashboardTeamRoute = DashboardTeamImport.update({
  id: '/team',
  path: '/team',
  getParentRoute: () => DashboardRoute,
} as any)

const DashboardStudentClubsRoute = DashboardStudentClubsImport.update({
  id: '/student-clubs',
  path: '/student-clubs',
  getParentRoute: () => DashboardRoute,
} as any)

const DashboardStudentChaptersRoute = DashboardStudentChaptersImport.update({
  id: '/student-chapters',
  path: '/student-chapters',
  getParentRoute: () => DashboardRoute,
} as any)

const DashboardStudentCampusRoute = DashboardStudentCampusImport.update({
  id: '/student-campus',
  path: '/student-campus',
  getParentRoute: () => DashboardRoute,
} as any)

const DashboardRolesRoute = DashboardRolesImport.update({
  id: '/roles',
  path: '/roles',
  getParentRoute: () => DashboardRoute,
} as any)

const DashboardProgramsRoute = DashboardProgramsImport.update({
  id: '/programs',
  path: '/programs',
  getParentRoute: () => DashboardRoute,
} as any)

const DashboardProgramAlumnisRoute = DashboardProgramAlumnisImport.update({
  id: '/program-alumnis',
  path: '/program-alumnis',
  getParentRoute: () => DashboardRoute,
} as any)

const DashboardOrganizationalStructureRoute =
  DashboardOrganizationalStructureImport.update({
    id: '/organizational-structure',
    path: '/organizational-structure',
    getParentRoute: () => DashboardRoute,
  } as any)

const DashboardMembersRoute = DashboardMembersImport.update({
  id: '/members',
  path: '/members',
  getParentRoute: () => DashboardRoute,
} as any)

const DashboardMajorCampusesRoute = DashboardMajorCampusesImport.update({
  id: '/major-campuses',
  path: '/major-campuses',
  getParentRoute: () => DashboardRoute,
} as any)

const DashboardHistoriesRoute = DashboardHistoriesImport.update({
  id: '/histories',
  path: '/histories',
  getParentRoute: () => DashboardRoute,
} as any)

const DashboardHelpCenterRoute = DashboardHelpCenterImport.update({
  id: '/help-center',
  path: '/help-center',
  getParentRoute: () => DashboardRoute,
} as any)

const DashboardFaqsRoute = DashboardFaqsImport.update({
  id: '/faqs',
  path: '/faqs',
  getParentRoute: () => DashboardRoute,
} as any)

const DashboardExternalOrganizationsRoute =
  DashboardExternalOrganizationsImport.update({
    id: '/external-organizations',
    path: '/external-organizations',
    getParentRoute: () => DashboardRoute,
  } as any)

const DashboardEventsRoute = DashboardEventsImport.update({
  id: '/events',
  path: '/events',
  getParentRoute: () => DashboardRoute,
} as any)

const DashboardEditProfileRoute = DashboardEditProfileImport.update({
  id: '/edit-profile',
  path: '/edit-profile',
  getParentRoute: () => DashboardRoute,
} as any)

const DashboardDashboardRoute = DashboardDashboardImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => DashboardRoute,
} as any)

const AuthLoginRoute = AuthLoginImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => AuthRoute,
} as any)

const DashboardRegistrantsEventidRoute =
  DashboardRegistrantsEventidImport.update({
    id: '/registrants/$event_id',
    path: '/registrants/$event_id',
    getParentRoute: () => DashboardRoute,
  } as any)

const DashboardEventDataEventidRoute = DashboardEventDataEventidImport.update({
  id: '/event-data/$event_id',
  path: '/event-data/$event_id',
  getParentRoute: () => DashboardRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/_auth': {
      id: '/_auth'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AuthImport
      parentRoute: typeof rootRoute
    }
    '/_dashboard': {
      id: '/_dashboard'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof DashboardImport
      parentRoute: typeof rootRoute
    }
    '/unauthorized': {
      id: '/unauthorized'
      path: '/unauthorized'
      fullPath: '/unauthorized'
      preLoaderRoute: typeof UnauthorizedImport
      parentRoute: typeof rootRoute
    }
    '/_auth/login': {
      id: '/_auth/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof AuthLoginImport
      parentRoute: typeof AuthImport
    }
    '/_dashboard/dashboard': {
      id: '/_dashboard/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardDashboardImport
      parentRoute: typeof DashboardImport
    }
    '/_dashboard/edit-profile': {
      id: '/_dashboard/edit-profile'
      path: '/edit-profile'
      fullPath: '/edit-profile'
      preLoaderRoute: typeof DashboardEditProfileImport
      parentRoute: typeof DashboardImport
    }
    '/_dashboard/events': {
      id: '/_dashboard/events'
      path: '/events'
      fullPath: '/events'
      preLoaderRoute: typeof DashboardEventsImport
      parentRoute: typeof DashboardImport
    }
    '/_dashboard/external-organizations': {
      id: '/_dashboard/external-organizations'
      path: '/external-organizations'
      fullPath: '/external-organizations'
      preLoaderRoute: typeof DashboardExternalOrganizationsImport
      parentRoute: typeof DashboardImport
    }
    '/_dashboard/faqs': {
      id: '/_dashboard/faqs'
      path: '/faqs'
      fullPath: '/faqs'
      preLoaderRoute: typeof DashboardFaqsImport
      parentRoute: typeof DashboardImport
    }
    '/_dashboard/help-center': {
      id: '/_dashboard/help-center'
      path: '/help-center'
      fullPath: '/help-center'
      preLoaderRoute: typeof DashboardHelpCenterImport
      parentRoute: typeof DashboardImport
    }
    '/_dashboard/histories': {
      id: '/_dashboard/histories'
      path: '/histories'
      fullPath: '/histories'
      preLoaderRoute: typeof DashboardHistoriesImport
      parentRoute: typeof DashboardImport
    }
    '/_dashboard/major-campuses': {
      id: '/_dashboard/major-campuses'
      path: '/major-campuses'
      fullPath: '/major-campuses'
      preLoaderRoute: typeof DashboardMajorCampusesImport
      parentRoute: typeof DashboardImport
    }
    '/_dashboard/members': {
      id: '/_dashboard/members'
      path: '/members'
      fullPath: '/members'
      preLoaderRoute: typeof DashboardMembersImport
      parentRoute: typeof DashboardImport
    }
    '/_dashboard/organizational-structure': {
      id: '/_dashboard/organizational-structure'
      path: '/organizational-structure'
      fullPath: '/organizational-structure'
      preLoaderRoute: typeof DashboardOrganizationalStructureImport
      parentRoute: typeof DashboardImport
    }
    '/_dashboard/program-alumnis': {
      id: '/_dashboard/program-alumnis'
      path: '/program-alumnis'
      fullPath: '/program-alumnis'
      preLoaderRoute: typeof DashboardProgramAlumnisImport
      parentRoute: typeof DashboardImport
    }
    '/_dashboard/programs': {
      id: '/_dashboard/programs'
      path: '/programs'
      fullPath: '/programs'
      preLoaderRoute: typeof DashboardProgramsImport
      parentRoute: typeof DashboardImport
    }
    '/_dashboard/roles': {
      id: '/_dashboard/roles'
      path: '/roles'
      fullPath: '/roles'
      preLoaderRoute: typeof DashboardRolesImport
      parentRoute: typeof DashboardImport
    }
    '/_dashboard/student-campus': {
      id: '/_dashboard/student-campus'
      path: '/student-campus'
      fullPath: '/student-campus'
      preLoaderRoute: typeof DashboardStudentCampusImport
      parentRoute: typeof DashboardImport
    }
    '/_dashboard/student-chapters': {
      id: '/_dashboard/student-chapters'
      path: '/student-chapters'
      fullPath: '/student-chapters'
      preLoaderRoute: typeof DashboardStudentChaptersImport
      parentRoute: typeof DashboardImport
    }
    '/_dashboard/student-clubs': {
      id: '/_dashboard/student-clubs'
      path: '/student-clubs'
      fullPath: '/student-clubs'
      preLoaderRoute: typeof DashboardStudentClubsImport
      parentRoute: typeof DashboardImport
    }
    '/_dashboard/team': {
      id: '/_dashboard/team'
      path: '/team'
      fullPath: '/team'
      preLoaderRoute: typeof DashboardTeamImport
      parentRoute: typeof DashboardImport
    }
    '/_dashboard/event-data/$event_id': {
      id: '/_dashboard/event-data/$event_id'
      path: '/event-data/$event_id'
      fullPath: '/event-data/$event_id'
      preLoaderRoute: typeof DashboardEventDataEventidImport
      parentRoute: typeof DashboardImport
    }
    '/_dashboard/registrants/$event_id': {
      id: '/_dashboard/registrants/$event_id'
      path: '/registrants/$event_id'
      fullPath: '/registrants/$event_id'
      preLoaderRoute: typeof DashboardRegistrantsEventidImport
      parentRoute: typeof DashboardImport
    }
  }
}

// Create and export the route tree

interface AuthRouteChildren {
  AuthLoginRoute: typeof AuthLoginRoute
}

const AuthRouteChildren: AuthRouteChildren = {
  AuthLoginRoute: AuthLoginRoute,
}

const AuthRouteWithChildren = AuthRoute._addFileChildren(AuthRouteChildren)

interface DashboardRouteChildren {
  DashboardDashboardRoute: typeof DashboardDashboardRoute
  DashboardEditProfileRoute: typeof DashboardEditProfileRoute
  DashboardEventsRoute: typeof DashboardEventsRoute
  DashboardExternalOrganizationsRoute: typeof DashboardExternalOrganizationsRoute
  DashboardFaqsRoute: typeof DashboardFaqsRoute
  DashboardHelpCenterRoute: typeof DashboardHelpCenterRoute
  DashboardHistoriesRoute: typeof DashboardHistoriesRoute
  DashboardMajorCampusesRoute: typeof DashboardMajorCampusesRoute
  DashboardMembersRoute: typeof DashboardMembersRoute
  DashboardOrganizationalStructureRoute: typeof DashboardOrganizationalStructureRoute
  DashboardProgramAlumnisRoute: typeof DashboardProgramAlumnisRoute
  DashboardProgramsRoute: typeof DashboardProgramsRoute
  DashboardRolesRoute: typeof DashboardRolesRoute
  DashboardStudentCampusRoute: typeof DashboardStudentCampusRoute
  DashboardStudentChaptersRoute: typeof DashboardStudentChaptersRoute
  DashboardStudentClubsRoute: typeof DashboardStudentClubsRoute
  DashboardTeamRoute: typeof DashboardTeamRoute
  DashboardEventDataEventidRoute: typeof DashboardEventDataEventidRoute
  DashboardRegistrantsEventidRoute: typeof DashboardRegistrantsEventidRoute
}

const DashboardRouteChildren: DashboardRouteChildren = {
  DashboardDashboardRoute: DashboardDashboardRoute,
  DashboardEditProfileRoute: DashboardEditProfileRoute,
  DashboardEventsRoute: DashboardEventsRoute,
  DashboardExternalOrganizationsRoute: DashboardExternalOrganizationsRoute,
  DashboardFaqsRoute: DashboardFaqsRoute,
  DashboardHelpCenterRoute: DashboardHelpCenterRoute,
  DashboardHistoriesRoute: DashboardHistoriesRoute,
  DashboardMajorCampusesRoute: DashboardMajorCampusesRoute,
  DashboardMembersRoute: DashboardMembersRoute,
  DashboardOrganizationalStructureRoute: DashboardOrganizationalStructureRoute,
  DashboardProgramAlumnisRoute: DashboardProgramAlumnisRoute,
  DashboardProgramsRoute: DashboardProgramsRoute,
  DashboardRolesRoute: DashboardRolesRoute,
  DashboardStudentCampusRoute: DashboardStudentCampusRoute,
  DashboardStudentChaptersRoute: DashboardStudentChaptersRoute,
  DashboardStudentClubsRoute: DashboardStudentClubsRoute,
  DashboardTeamRoute: DashboardTeamRoute,
  DashboardEventDataEventidRoute: DashboardEventDataEventidRoute,
  DashboardRegistrantsEventidRoute: DashboardRegistrantsEventidRoute,
}

const DashboardRouteWithChildren = DashboardRoute._addFileChildren(
  DashboardRouteChildren,
)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '': typeof DashboardRouteWithChildren
  '/unauthorized': typeof UnauthorizedRoute
  '/login': typeof AuthLoginRoute
  '/dashboard': typeof DashboardDashboardRoute
  '/edit-profile': typeof DashboardEditProfileRoute
  '/events': typeof DashboardEventsRoute
  '/external-organizations': typeof DashboardExternalOrganizationsRoute
  '/faqs': typeof DashboardFaqsRoute
  '/help-center': typeof DashboardHelpCenterRoute
  '/histories': typeof DashboardHistoriesRoute
  '/major-campuses': typeof DashboardMajorCampusesRoute
  '/members': typeof DashboardMembersRoute
  '/organizational-structure': typeof DashboardOrganizationalStructureRoute
  '/program-alumnis': typeof DashboardProgramAlumnisRoute
  '/programs': typeof DashboardProgramsRoute
  '/roles': typeof DashboardRolesRoute
  '/student-campus': typeof DashboardStudentCampusRoute
  '/student-chapters': typeof DashboardStudentChaptersRoute
  '/student-clubs': typeof DashboardStudentClubsRoute
  '/team': typeof DashboardTeamRoute
  '/event-data/$event_id': typeof DashboardEventDataEventidRoute
  '/registrants/$event_id': typeof DashboardRegistrantsEventidRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '': typeof DashboardRouteWithChildren
  '/unauthorized': typeof UnauthorizedRoute
  '/login': typeof AuthLoginRoute
  '/dashboard': typeof DashboardDashboardRoute
  '/edit-profile': typeof DashboardEditProfileRoute
  '/events': typeof DashboardEventsRoute
  '/external-organizations': typeof DashboardExternalOrganizationsRoute
  '/faqs': typeof DashboardFaqsRoute
  '/help-center': typeof DashboardHelpCenterRoute
  '/histories': typeof DashboardHistoriesRoute
  '/major-campuses': typeof DashboardMajorCampusesRoute
  '/members': typeof DashboardMembersRoute
  '/organizational-structure': typeof DashboardOrganizationalStructureRoute
  '/program-alumnis': typeof DashboardProgramAlumnisRoute
  '/programs': typeof DashboardProgramsRoute
  '/roles': typeof DashboardRolesRoute
  '/student-campus': typeof DashboardStudentCampusRoute
  '/student-chapters': typeof DashboardStudentChaptersRoute
  '/student-clubs': typeof DashboardStudentClubsRoute
  '/team': typeof DashboardTeamRoute
  '/event-data/$event_id': typeof DashboardEventDataEventidRoute
  '/registrants/$event_id': typeof DashboardRegistrantsEventidRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/_auth': typeof AuthRouteWithChildren
  '/_dashboard': typeof DashboardRouteWithChildren
  '/unauthorized': typeof UnauthorizedRoute
  '/_auth/login': typeof AuthLoginRoute
  '/_dashboard/dashboard': typeof DashboardDashboardRoute
  '/_dashboard/edit-profile': typeof DashboardEditProfileRoute
  '/_dashboard/events': typeof DashboardEventsRoute
  '/_dashboard/external-organizations': typeof DashboardExternalOrganizationsRoute
  '/_dashboard/faqs': typeof DashboardFaqsRoute
  '/_dashboard/help-center': typeof DashboardHelpCenterRoute
  '/_dashboard/histories': typeof DashboardHistoriesRoute
  '/_dashboard/major-campuses': typeof DashboardMajorCampusesRoute
  '/_dashboard/members': typeof DashboardMembersRoute
  '/_dashboard/organizational-structure': typeof DashboardOrganizationalStructureRoute
  '/_dashboard/program-alumnis': typeof DashboardProgramAlumnisRoute
  '/_dashboard/programs': typeof DashboardProgramsRoute
  '/_dashboard/roles': typeof DashboardRolesRoute
  '/_dashboard/student-campus': typeof DashboardStudentCampusRoute
  '/_dashboard/student-chapters': typeof DashboardStudentChaptersRoute
  '/_dashboard/student-clubs': typeof DashboardStudentClubsRoute
  '/_dashboard/team': typeof DashboardTeamRoute
  '/_dashboard/event-data/$event_id': typeof DashboardEventDataEventidRoute
  '/_dashboard/registrants/$event_id': typeof DashboardRegistrantsEventidRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | ''
    | '/unauthorized'
    | '/login'
    | '/dashboard'
    | '/edit-profile'
    | '/events'
    | '/external-organizations'
    | '/faqs'
    | '/help-center'
    | '/histories'
    | '/major-campuses'
    | '/members'
    | '/organizational-structure'
    | '/program-alumnis'
    | '/programs'
    | '/roles'
    | '/student-campus'
    | '/student-chapters'
    | '/student-clubs'
    | '/team'
    | '/event-data/$event_id'
    | '/registrants/$event_id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | ''
    | '/unauthorized'
    | '/login'
    | '/dashboard'
    | '/edit-profile'
    | '/events'
    | '/external-organizations'
    | '/faqs'
    | '/help-center'
    | '/histories'
    | '/major-campuses'
    | '/members'
    | '/organizational-structure'
    | '/program-alumnis'
    | '/programs'
    | '/roles'
    | '/student-campus'
    | '/student-chapters'
    | '/student-clubs'
    | '/team'
    | '/event-data/$event_id'
    | '/registrants/$event_id'
  id:
    | '__root__'
    | '/'
    | '/_auth'
    | '/_dashboard'
    | '/unauthorized'
    | '/_auth/login'
    | '/_dashboard/dashboard'
    | '/_dashboard/edit-profile'
    | '/_dashboard/events'
    | '/_dashboard/external-organizations'
    | '/_dashboard/faqs'
    | '/_dashboard/help-center'
    | '/_dashboard/histories'
    | '/_dashboard/major-campuses'
    | '/_dashboard/members'
    | '/_dashboard/organizational-structure'
    | '/_dashboard/program-alumnis'
    | '/_dashboard/programs'
    | '/_dashboard/roles'
    | '/_dashboard/student-campus'
    | '/_dashboard/student-chapters'
    | '/_dashboard/student-clubs'
    | '/_dashboard/team'
    | '/_dashboard/event-data/$event_id'
    | '/_dashboard/registrants/$event_id'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthRoute: typeof AuthRouteWithChildren
  DashboardRoute: typeof DashboardRouteWithChildren
  UnauthorizedRoute: typeof UnauthorizedRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthRoute: AuthRouteWithChildren,
  DashboardRoute: DashboardRouteWithChildren,
  UnauthorizedRoute: UnauthorizedRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/_auth",
        "/_dashboard",
        "/unauthorized"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/_auth": {
      "filePath": "_auth.tsx",
      "children": [
        "/_auth/login"
      ]
    },
    "/_dashboard": {
      "filePath": "_dashboard.tsx",
      "children": [
        "/_dashboard/dashboard",
        "/_dashboard/edit-profile",
        "/_dashboard/events",
        "/_dashboard/external-organizations",
        "/_dashboard/faqs",
        "/_dashboard/help-center",
        "/_dashboard/histories",
        "/_dashboard/major-campuses",
        "/_dashboard/members",
        "/_dashboard/organizational-structure",
        "/_dashboard/program-alumnis",
        "/_dashboard/programs",
        "/_dashboard/roles",
        "/_dashboard/student-campus",
        "/_dashboard/student-chapters",
        "/_dashboard/student-clubs",
        "/_dashboard/team",
        "/_dashboard/event-data/$event_id",
        "/_dashboard/registrants/$event_id"
      ]
    },
    "/unauthorized": {
      "filePath": "unauthorized.tsx"
    },
    "/_auth/login": {
      "filePath": "_auth/login.tsx",
      "parent": "/_auth"
    },
    "/_dashboard/dashboard": {
      "filePath": "_dashboard/dashboard.tsx",
      "parent": "/_dashboard"
    },
    "/_dashboard/edit-profile": {
      "filePath": "_dashboard/edit-profile.tsx",
      "parent": "/_dashboard"
    },
    "/_dashboard/events": {
      "filePath": "_dashboard/events.tsx",
      "parent": "/_dashboard"
    },
    "/_dashboard/external-organizations": {
      "filePath": "_dashboard/external-organizations.tsx",
      "parent": "/_dashboard"
    },
    "/_dashboard/faqs": {
      "filePath": "_dashboard/faqs.tsx",
      "parent": "/_dashboard"
    },
    "/_dashboard/help-center": {
      "filePath": "_dashboard/help-center.tsx",
      "parent": "/_dashboard"
    },
    "/_dashboard/histories": {
      "filePath": "_dashboard/histories.tsx",
      "parent": "/_dashboard"
    },
    "/_dashboard/major-campuses": {
      "filePath": "_dashboard/major-campuses.tsx",
      "parent": "/_dashboard"
    },
    "/_dashboard/members": {
      "filePath": "_dashboard/members.tsx",
      "parent": "/_dashboard"
    },
    "/_dashboard/organizational-structure": {
      "filePath": "_dashboard/organizational-structure.tsx",
      "parent": "/_dashboard"
    },
    "/_dashboard/program-alumnis": {
      "filePath": "_dashboard/program-alumnis.tsx",
      "parent": "/_dashboard"
    },
    "/_dashboard/programs": {
      "filePath": "_dashboard/programs.tsx",
      "parent": "/_dashboard"
    },
    "/_dashboard/roles": {
      "filePath": "_dashboard/roles.tsx",
      "parent": "/_dashboard"
    },
    "/_dashboard/student-campus": {
      "filePath": "_dashboard/student-campus.tsx",
      "parent": "/_dashboard"
    },
    "/_dashboard/student-chapters": {
      "filePath": "_dashboard/student-chapters.tsx",
      "parent": "/_dashboard"
    },
    "/_dashboard/student-clubs": {
      "filePath": "_dashboard/student-clubs.tsx",
      "parent": "/_dashboard"
    },
    "/_dashboard/team": {
      "filePath": "_dashboard/team.tsx",
      "parent": "/_dashboard"
    },
    "/_dashboard/event-data/$event_id": {
      "filePath": "_dashboard/event-data.$event_id.tsx",
      "parent": "/_dashboard"
    },
    "/_dashboard/registrants/$event_id": {
      "filePath": "_dashboard/registrants.$event_id.tsx",
      "parent": "/_dashboard"
    }
  }
}
ROUTE_MANIFEST_END */
